#!/bin/bash
# Bash needed for the character encodings below.
#
# Run checks for ./isutf8.
#
# Lars Wirzenius <liw@iki.fi>

failed=0

check() {
	printf "$2" | ./isutf8 -q
	ret=$?
	if [ $ret != $1 ]; then
		echo "Failure:"
		echo "  input: $2"
		echo "  expected: $1"
		echo "  got: $ret"
		failed=1
	fi
}

check 0 ''
check 0 'a'
check 0 'ab'
check 0 '\xc2\xa9'

check 1 '\xc2'
check 1 '\xc2\x20'
check 1 '\x20\xc2'

exit $failed
